version: "2.1"
services:
  microservices:
    build: .
    image: arc1999/goinvest
    env_file:
      - ./envvar.env
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db
  db:
    image: mysql
    container_name: cloudserver

    environment: 
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=Stocks'
    ports: 
      - '3306:3306'  
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10